#!/bin/sh
# This makes touch and pen input work properly even when external monitors are connected
xinput map-to-output 'SynPS/2 Synaptics TouchPad' eDP1
xinput map-to-output 'ELAN Touchscreen' eDP1
xinput map-to-output 'Wacom ISDv4 EC Pen stylus' eDP1
xinput map-to-output 'Wacom ISDv4 EC Pen eraser' eDP1

true
